import { randomBytes, randomUUID } from 'node:crypto';
import { BrowserContext, Locator, Page, chromium } from 'playwright';
import { config } from './config.js';
import { AccountLockManager } from './account-lock-manager.js';
import { ApprovalRecord, ApprovalStore } from './approval-store.js';
import { detectSecurityState } from './facebook-page.js';
import { ApiError, SessionStatus, WorkerResponse } from './types.js';

const reactions = ['like', 'love', 'care', 'haha', 'wow', 'sad', 'angry'] as const;
type Reaction = typeof reactions[number];
type ActionRequest = { postUrl: string; action: 'react'; reaction: Reaction; approvalId: string } | { postUrl: string; action: 'comment'; comment: string; approvalId: string };
interface ActiveSession { accountId: string; sessionId: string; viewerToken: string; context: BrowserContext; page: Page; release: () => Promise<void>; timeout: NodeJS.Timeout; status: SessionStatus; pending?: () => Promise<WorkerResponse>; }

export class SessionManager {
  private sessions = new Map<string, ActiveSession>(); private byAccount = new Map<string, string>();
  constructor(private locks: AccountLockManager, private approvals = new ApprovalStore(`${config.PROFILE_ROOT}/.approvals`)) {}
  private viewer(session: ActiveSession) { const base = config.PUBLIC_BASE_URL.replace(/\/$/, ''); const token = encodeURIComponent(session.viewerToken); return `${base}/novnc/vnc.html?autoconnect=true&resize=scale&path=novnc/websockify%3Ftoken%3D${token}&token=${token}`; }
  private response(accountId: string, session?: ActiveSession, overrides: Partial<WorkerResponse> = {}): WorkerResponse { return { accountId, sessionId: session?.sessionId ?? null, status: session?.status ?? 'idle', viewerUrl: session ? this.viewer(session) : null, loggedIn: false, errorCode: null, errorMessage: null, ...overrides }; }
  private requireActive(accountId: string) { const session = this.sessions.get(this.byAccount.get(accountId) ?? ''); if (!session) throw new ApiError('SESSION_NOT_FOUND', 'No active browser session exists for this account.', 404); return session; }
  canView(token: string | undefined) { return !!token && [...this.sessions.values()].some((x) => x.viewerToken === token); }
  private async open(accountId: string, interactive = false, proxy?: string): Promise<ActiveSession> {
    if (this.byAccount.has(accountId)) throw new ApiError('SESSION_ALREADY_ACTIVE', 'This account already has an active browser session.', 409);
    if (this.sessions.size >= config.MAX_ACTIVE_BROWSERS) throw new ApiError('BROWSER_CAPACITY_REACHED', 'Global active browser limit has been reached.', 429);
    const sessionId = randomUUID(); const release = await this.locks.acquire(accountId, sessionId);
    try {
      // Per-account proxy takes priority; falls back to global BROWSER_PROXY env var.
      const resolvedProxy = proxy ?? config.BROWSER_PROXY;
      let proxySettings: any = {};
      if (resolvedProxy) {
        try {
          const u = new URL(resolvedProxy);
          if (u.username || u.password) {
            proxySettings = {
              proxy: {
                server: `${u.protocol}//${u.host}`,
                username: decodeURIComponent(u.username),
                password: decodeURIComponent(u.password)
              }
            };
          } else {
            proxySettings = { proxy: { server: resolvedProxy } };
          }
        } catch {
          proxySettings = { proxy: { server: resolvedProxy } };
        }
      }
      const context = await chromium.launchPersistentContext(this.locks.profilePath(accountId), { headless: !interactive, viewport: { width: 1280, height: 720 }, ...proxySettings, args: ['--no-sandbox', '--disable-dev-shm-usage', '--no-first-run', '--no-default-browser-check', '--disable-background-networking', '--disable-gpu', '--disable-software-rasterizer', '--disable-extensions', '--disable-default-apps', '--disable-sync', '--disable-translate', '--disable-background-timer-throttling', '--disable-backgrounding-occluded-windows', '--disable-renderer-backgrounding', '--disable-features=TranslateUI,BlinkGenPropertyTrees', '--mute-audio', '--hide-scrollbars', '--metrics-recording-only', '--memory-pressure-off', '--js-flags=--max-old-space-size=256', '--disable-blink-features=AutomationControlled'] });

      const page = context.pages()[0] ?? await context.newPage();
      const session = { accountId, sessionId, viewerToken: randomBytes(24).toString('base64url'), context, page, release, status: 'browser_ready' as SessionStatus, timeout: undefined as unknown as NodeJS.Timeout };
      session.timeout = setTimeout(() => void this.close(session, 'timed_out'), config.SESSION_TIMEOUT_SECONDS * 1000);
      this.sessions.set(sessionId, session); this.byAccount.set(accountId, sessionId); context.once('close', () => void this.externalClose(session)); return session;
    } catch (e) { await release(); throw e; }
  }
  private async cookiesLoggedIn(context: BrowserContext) { const c = await context.cookies('https://www.facebook.com'); return c.some((x) => x.name === 'c_user' && x.value) && c.some((x) => x.name === 'xs' && x.value); }
  private async check(page: Page) { const state = await detectSecurityState(page); return state === 'ready' && await this.cookiesLoggedIn(page.context()); }
  async start(accountId: string, proxy?: string) { const session = await this.open(accountId, true, proxy); await session.page.goto('https://www.facebook.com/', { waitUntil: 'domcontentloaded', timeout: 45_000 }); const state = await detectSecurityState(session.page); session.status = state === 'ready' ? 'browser_ready' : 'manual_intervention_required'; return this.response(accountId, session, { loggedIn: state === 'ready' && await this.cookiesLoggedIn(session.context) }); }
  async get(accountId: string) { const s = this.sessions.get(this.byAccount.get(accountId) ?? ''); return s ? this.response(accountId, s, { loggedIn: await this.cookiesLoggedIn(s.context).catch(() => false) }) : this.response(accountId); }
  async continue(accountId: string) { const s = this.requireActive(accountId); if (!await this.check(s.page)) { s.status = 'manual_intervention_required'; return this.response(accountId, s, { errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Complete Facebook login or verification in the browser, then continue.' }); } if (s.pending) return s.pending(); await this.close(s, 'completed'); return this.response(accountId, undefined, { sessionId: s.sessionId, status: 'completed', loggedIn: true }); }
  async cancel(accountId: string) { const s = this.requireActive(accountId); await this.close(s, 'cancelled'); return this.response(accountId, undefined, { sessionId: s.sessionId, status: 'cancelled' }); }
  private async manual(accountId: string, current: ActiveSession, url: string, proxy?: string, pending?: () => Promise<WorkerResponse>) { await this.close(current, 'cancelled'); const session = await this.open(accountId, true, proxy); await session.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45_000 }); session.status = 'manual_intervention_required'; session.pending = pending; return session; }
  async validate(accountId: string, proxy?: string) { const current = this.sessions.get(this.byAccount.get(accountId) ?? ''); if (current) return this.response(accountId, current, { loggedIn: await this.check(current.page) }); const s = await this.open(accountId, false, proxy); try { await s.page.goto('https://www.facebook.com/', { waitUntil: 'domcontentloaded', timeout: 45_000 }); const loggedIn = await this.check(s.page); if (!loggedIn) { const m = await this.manual(accountId, s, 'https://www.facebook.com/', proxy); return this.response(accountId, m, { loggedIn: false, errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Login or verification is required.' }); } await this.close(s, 'completed'); return this.response(accountId, undefined, { sessionId: s.sessionId, status: 'completed', loggedIn: true }); } catch (e) { await this.close(s, 'failed'); throw e; } }
  private async usePage(accountId: string, url: string, proxy?: string) { const existing = this.sessions.get(this.byAccount.get(accountId) ?? ''); const s = existing ?? await this.open(accountId, false, proxy); await s.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45_000 }); return { s, transient: !existing }; }
  async inspect(accountId: string, postUrl: string) { const { s, transient } = await this.usePage(accountId, postUrl); const security = await detectSecurityState(s.page); if (security !== 'ready' || !await this.cookiesLoggedIn(s.context)) { const m = transient ? await this.manual(accountId, s, postUrl) : s; m.status = 'manual_intervention_required'; return this.response(accountId, m, { errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Login or verification is required before inspecting this post.' }); } const result = await this.inspectTargetPost(s.page); if (transient) await this.close(s, 'completed'); return this.response(accountId, transient ? undefined : s, { status: 'completed', loggedIn: true, result }); }
  async execute(accountId: string, input: ActionRequest) {
    const fingerprint = this.approvals.fingerprint(accountId, input.postUrl, input.action, input.action === 'react' ? input.reaction : undefined, input.action === 'comment' ? input.comment : undefined);
    const started = await this.approvals.begin(accountId, input.approvalId, fingerprint);
    if (started.duplicate) {
      if (started.record.status === 'running') await this.approvals.complete(started.record, 'outcome_unknown');
      const status = started.record.status === 'running' ? 'outcome_unknown' : started.record.status as SessionStatus;
      return this.response(accountId, undefined, { status, errorCode: status === 'outcome_unknown' ? 'OUTCOME_UNKNOWN' : null, result: { approvalId: input.approvalId, idempotent: true, previousState: started.record.previousState ?? null, finalState: started.record.finalState ?? null } });
    }
    try { return await this.perform(accountId, input, started.record); }
    catch { await this.approvals.complete(started.record, 'outcome_unknown'); return this.response(accountId, undefined, { status: 'outcome_unknown', errorCode: 'OUTCOME_UNKNOWN', errorMessage: 'The action could not start or be confirmed; it was not retried.', result: { approvalId: input.approvalId } }); }
  }
  private async perform(accountId: string, input: ActionRequest, record: ApprovalRecord): Promise<WorkerResponse> {
    const { s, transient } = await this.usePage(accountId, input.postUrl); const security = await detectSecurityState(s.page);
    if (security !== 'ready' || !await this.cookiesLoggedIn(s.context)) { const m = transient ? await this.manual(accountId, s, input.postUrl, undefined, () => this.perform(accountId, input, record)) : s; m.status = 'manual_intervention_required'; m.pending = () => this.perform(accountId, input, record); await this.approvals.complete(record, 'manual_intervention_required'); return this.response(accountId, m, { errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Complete Facebook verification in the browser, then press Continue.' }); }
    s.status = 'running';
    try {
      const result = input.action === 'react' ? await this.react(s.page, input.reaction) : await this.comment(s.page, input.comment);
      if (result.confirmed) { await this.approvals.complete(record, 'completed', result.previous, result.final); if (transient) await this.close(s, 'completed'); return this.response(accountId, transient ? undefined : s, { status: 'completed', loggedIn: true, result: { approvalId: input.approvalId, previousState: result.previous, finalState: result.final, diagnostic: result.diagnostic } }); }
      await this.approvals.complete(record, 'outcome_unknown', result.previous, result.final); s.status = 'outcome_unknown'; return this.response(accountId, s, { errorCode: 'OUTCOME_UNKNOWN', errorMessage: 'The final Facebook state could not be confirmed.', result: { approvalId: input.approvalId, previousState: result.previous, finalState: result.final, diagnostic: result.diagnostic } });
    } catch {
      const security = await detectSecurityState(s.page).catch(() => 'ready');
      if (security !== 'ready') { const m = transient ? await this.manual(accountId, s, input.postUrl, undefined, () => this.perform(accountId, input, record)) : s; m.status = 'manual_intervention_required'; m.pending = () => this.perform(accountId, input, record); await this.approvals.complete(record, 'manual_intervention_required'); return this.response(accountId, m, { errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Facebook requires manual verification before this approved action can finish.' }); }
      await this.approvals.complete(record, 'outcome_unknown'); s.status = 'outcome_unknown'; return this.response(accountId, s, { errorCode: 'OUTCOME_UNKNOWN', errorMessage: 'The action result could not be confirmed; it was not retried.', result: { approvalId: input.approvalId } }); }
  }
  private async postScope(page: Page): Promise<Locator> { const body = page.locator('body'); let postId = ''; try { postId = new URL(page.url()).pathname.split('/').find((part) => /^pfbid[A-Za-z0-9]+$/.test(part) || /^\d{6,}$/.test(part)) ?? ''; } catch { return body; } if (postId) { const permalink = page.locator(`a[href*="${postId}"]`).filter({ visible: true }).first(); if (await permalink.count()) { const article = permalink.locator('xpath=ancestor::*[@role="article"][1]'); if (await article.count()) return article; } } const primaryReactions = page.locator('[role="button"][aria-label^="React with "]').filter({ visible: true }); if (await primaryReactions.count()) { const article = primaryReactions.last().locator('xpath=ancestor::*[@role="article"][1]'); if (await article.count()) return article; } return body; }
  private async targetAuthor(page: Page): Promise<string | null> { let owner = ''; try { owner = new URL(page.url()).pathname.split('/').filter(Boolean)[0] ?? ''; } catch { return null; } if (!owner) return null; const links = page.locator(`a[href*="/${owner}"]`).filter({ visible: true }); const texts = await links.allInnerTexts(); return texts.map((text) => text.trim()).find((text) => text.length > 2 && !/^\d+[smhdwy]$/i.test(text)) ?? null; }
  private async targetPostButton(page: Page, author: string, kind: 'reaction' | 'comment'): Promise<Locator | null> { const selector = kind === 'comment' ? '[role="button"][aria-label^="Comment on "]' : '[role="button"][aria-label*="post"]'; const buttons = page.locator(selector).filter({ visible: true }); const count = await buttons.count(); if (!count) return null; const index = await buttons.evaluateAll((elements, input) => elements.findIndex((element) => { const label = (element.getAttribute('aria-label') ?? '').toLowerCase(); return label.includes(input.author.toLowerCase()) && (input.kind === 'reaction' ? /(react with|remove|unlike|reaction)/.test(label) : label.startsWith('comment on ')); }), { author, kind }); return index >= 0 ? buttons.nth(index) : buttons.last(); }
  private async targetPostScope(page: Page): Promise<Locator> { const author = await this.targetAuthor(page); if (!author) return this.postScope(page); const reaction = await this.targetPostButton(page, author, 'reaction'); if (!reaction) return this.postScope(page); let owner = ''; try { owner = new URL(page.url()).pathname.split('/').filter(Boolean)[0] ?? ''; } catch { return this.postScope(page); } if (owner) { const scope = reaction.locator(`xpath=ancestor::*[.//a[contains(@href, "/${owner}")]][1]`); if (await scope.count()) return scope; } const article = reaction.locator('xpath=ancestor::*[@role="article"][1]'); return await article.count() ? article : page.locator('body'); }
  private async inspectTargetPost(page: Page): Promise<Record<string, unknown>> { const author = await this.targetAuthor(page); if (!author) throw new ApiError('TARGET_POST_NOT_FOUND', 'Could not identify the linked post author.'); const reactionControl = await this.targetPostButton(page, author, 'reaction'); if (!reactionControl) throw new ApiError('TARGET_POST_NOT_FOUND', 'Could not identify the linked post controls.'); const messages = page.locator('[data-ad-preview="message"], [data-ad-comet-preview="message"]').filter({ visible: true }); const reactionHandle = await reactionControl.elementHandle(); if (!reactionHandle || !await messages.count()) throw new ApiError('TARGET_POST_NOT_FOUND', 'Could not identify the visible post message.'); const messageIndex = await messages.evaluateAll((elements, target) => { const distance = (a: Element, b: Element) => { const ancestors = new Map<Element, number>(); let node: Element | null = a; let depth = 0; while (node) { ancestors.set(node, depth++); node = node.parentElement; } node = b; depth = 0; while (node) { const first = ancestors.get(node); if (first !== undefined) return first + depth; depth++; node = node.parentElement; } return Number.MAX_SAFE_INTEGER; }; let best = 0; let bestDistance = Number.MAX_SAFE_INTEGER; elements.forEach((element, index) => { const current = distance(element, target as Element); if (current < bestDistance) { best = index; bestDistance = current; } }); return best; }, reactionHandle); const visiblePostText = (await messages.nth(messageIndex).innerText()).trim().slice(0, 12000); return { visiblePostText, visibleAuthorName: author }; }
  private async visibleControl(page: Page, label: string, scope?: Locator): Promise<Locator | null> { const root = scope ?? page.locator('body'); const text = root.getByText(label, { exact: true }).filter({ visible: true }).first(); if (!await text.count()) return null; const button = text.locator('xpath=ancestor-or-self::*[@role="button"][1]'); return await button.count() ? button : text; }
  private async readReactionControl(control: Locator | null) { if (!control) return null; const state = await control.evaluate((element) => { const label = `${element.getAttribute('aria-label') ?? ''} ${element.textContent ?? ''}`.toLowerCase(); return { label, pressed: element.getAttribute('aria-pressed') === 'true', color: getComputedStyle(element).color }; }); const reaction = reactions.find((value) => state.pressed && state.label.includes(value) || state.label.includes(`remove ${value}`) || state.label.includes(`un${value}`)) ?? null; return { reaction, color: state.color }; }
  private async visibleComposer(page: Page, anchor?: Locator): Promise<Locator | null> { const composers = page.locator('[contenteditable="true"][role="textbox"], textarea').filter({ visible: true }); const count = await composers.count(); if (!count) return null; if (!anchor) return composers.first(); const box = await anchor.boundingBox(); if (!box) return composers.first(); const index = await composers.evaluateAll((elements, y) => { let best = 0; let distance = Number.POSITIVE_INFINITY; elements.forEach((element, i) => { const rect = element.getBoundingClientRect(); const current = Math.abs(rect.top - y); if (current < distance) { best = i; distance = current; } }); return best; }, box.y); return composers.nth(index); }
  private async react(page: Page, requested: Reaction) { const author = await this.targetAuthor(page); if (!author) return { confirmed: false, previous: null, final: null, diagnostic: 'target_post_author_not_found' }; let control = await this.targetPostButton(page, author, 'reaction'); if (!control) return { confirmed: false, previous: null, final: null, diagnostic: 'target_post_reaction_not_found' }; const before = await this.readReactionControl(control); const previous = before?.reaction ?? null; if (previous === requested) return { confirmed: true, previous, final: requested, diagnostic: 'already_active' }; if (requested === 'like') await control.click(); else { await control.hover(); await page.waitForTimeout(900); const choice = await this.visibleControl(page, requested[0].toUpperCase() + requested.slice(1)); if (!choice) return { confirmed: false, previous, final: null, diagnostic: 'reaction_choice_not_found' }; await choice.click(); } await page.mouse.move(0, 0); await page.waitForTimeout(1200); control = await this.targetPostButton(page, author, 'reaction'); const after = await this.readReactionControl(control); const colorChangedLike = requested === 'like' && !!before && !!after && before.color !== after.color; const confirmed = after?.reaction === requested || colorChangedLike; return { confirmed, previous, final: confirmed ? requested : after?.reaction ?? null, diagnostic: confirmed ? 'confirmed_from_target_post' : 'reaction_state_not_confirmed' }; }
  private async comment(page: Page, text: string) { if (!text.trim()) throw new ApiError('INVALID_COMMENT', 'comment must be non-empty.'); const author = await this.targetAuthor(page); if (!author) return { confirmed: false, previous: null, final: null, diagnostic: 'target_post_author_not_found' }; const commentButton = await this.targetPostButton(page, author, 'comment'); if (!commentButton) return { confirmed: false, previous: null, final: null, diagnostic: 'target_post_comment_not_found' }; const before = await page.locator('body').innerText(); const beforeCount = before.split(text).length - 1; await commentButton.click(); await page.waitForTimeout(600); const composer = await this.visibleComposer(page, commentButton); if (!composer) return { confirmed: false, previous: null, final: null, diagnostic: 'comment_composer_not_found' }; await composer.click(); await composer.fill(text); await composer.press('Enter'); await page.waitForTimeout(2200); const after = await page.locator('body').innerText(); const confirmed = after.split(text).length - 1 > beforeCount; return { confirmed, previous: null, final: confirmed ? 'comment_present' : null, diagnostic: confirmed ? 'comment_visible_on_target_post' : 'comment_not_visible_after_submit' }; }
  private async close(s: ActiveSession, status: SessionStatus) { clearTimeout(s.timeout); this.sessions.delete(s.sessionId); this.byAccount.delete(s.accountId); try { await s.context.close(); } finally { await s.release(); } s.status = status; }
  private async externalClose(s: ActiveSession) { if (!this.sessions.has(s.sessionId)) return; clearTimeout(s.timeout); this.sessions.delete(s.sessionId); this.byAccount.delete(s.accountId); await s.release(); }
  async shutdown() { await Promise.all([...this.sessions.values()].map((s) => this.close(s, 'cancelled'))); }
}
