import { randomBytes, randomUUID } from 'node:crypto';
import { BrowserContext, Page, chromium } from 'playwright';
import { config } from './config.js';
import { AccountLockManager } from './account-lock-manager.js';
import { ApprovalRecord, ApprovalStore } from './approval-store.js';
import { detectSecurityState, inspectVisiblePost } from './facebook-page.js';
import { ApiError, SessionStatus, WorkerResponse } from './types.js';

const reactions = ['like', 'love', 'care', 'haha', 'wow', 'sad', 'angry'] as const;
type Reaction = typeof reactions[number];
type ActionRequest = { postUrl: string; action: 'react'; reaction: Reaction; approvalId: string } | { postUrl: string; action: 'comment'; comment: string; approvalId: string };
interface ActiveSession { accountId: string; sessionId: string; viewerToken: string; context: BrowserContext; page: Page; release: () => Promise<void>; timeout: NodeJS.Timeout; status: SessionStatus; pending?: () => Promise<WorkerResponse>; }

export class SessionManager {
  private sessions = new Map<string, ActiveSession>(); private byAccount = new Map<string, string>();
  constructor(private locks: AccountLockManager, private approvals = new ApprovalStore(`${config.PROFILE_ROOT}/.approvals`)) {}
  private viewer(session: ActiveSession) { const base = config.PUBLIC_BASE_URL.replace(/\/$/, ''); const token = encodeURIComponent(session.viewerToken); return `${base}/novnc/vnc.html?autoconnect=true&resize=scale&path=novnc/websockify%3Ftoken%3D${token}&token=${token}`; }
  private response(accountId: string, session?: ActiveSession, overrides: Partial<WorkerResponse> = {}): WorkerResponse { return { accountId, sessionId: session?.sessionId ?? null, status: session?.status ?? 'idle', viewerUrl: session ? this.viewer(session) : null, loggedIn: false, errorCode: null, errorMessage: null, ...overrides }; }
  private requireActive(accountId: string) { const session = this.sessions.get(this.byAccount.get(accountId) ?? ''); if (!session) throw new ApiError('SESSION_NOT_FOUND', 'No active browser session exists for this account.', 404); return session; }
  canView(token: string | undefined) { return !!token && [...this.sessions.values()].some((x) => x.viewerToken === token); }
  private async open(accountId: string, interactive = false): Promise<ActiveSession> {
    if (this.byAccount.has(accountId)) throw new ApiError('SESSION_ALREADY_ACTIVE', 'This account already has an active browser session.', 409);
    if (this.sessions.size >= config.MAX_ACTIVE_BROWSERS) throw new ApiError('BROWSER_CAPACITY_REACHED', 'Global active browser limit has been reached.', 429);
    const sessionId = randomUUID(); const release = await this.locks.acquire(accountId, sessionId);
    try {
      const context = await chromium.launchPersistentContext(this.locks.profilePath(accountId), { headless: !interactive, viewport: { width: 1440, height: 900 }, args: ['--no-sandbox', '--disable-dev-shm-usage', '--no-first-run', '--no-default-browser-check', '--disable-background-networking'] });
      const page = context.pages()[0] ?? await context.newPage();
      const session = { accountId, sessionId, viewerToken: randomBytes(24).toString('base64url'), context, page, release, status: 'browser_ready' as SessionStatus, timeout: undefined as unknown as NodeJS.Timeout };
      session.timeout = setTimeout(() => void this.close(session, 'timed_out'), config.SESSION_TIMEOUT_SECONDS * 1000);
      this.sessions.set(sessionId, session); this.byAccount.set(accountId, sessionId); context.once('close', () => void this.externalClose(session)); return session;
    } catch (e) { await release(); throw e; }
  }
  private async cookiesLoggedIn(context: BrowserContext) { const c = await context.cookies('https://www.facebook.com'); return c.some((x) => x.name === 'c_user' && x.value) && c.some((x) => x.name === 'xs' && x.value); }
  private async check(page: Page) { const state = await detectSecurityState(page); return state === 'ready' && await this.cookiesLoggedIn(page.context()); }
  async start(accountId: string) { const session = await this.open(accountId, true); await session.page.goto('https://www.facebook.com/', { waitUntil: 'domcontentloaded', timeout: 45_000 }); const state = await detectSecurityState(session.page); session.status = state === 'ready' ? 'browser_ready' : 'manual_intervention_required'; return this.response(accountId, session, { loggedIn: state === 'ready' && await this.cookiesLoggedIn(session.context) }); }
  async get(accountId: string) { const s = this.sessions.get(this.byAccount.get(accountId) ?? ''); return s ? this.response(accountId, s, { loggedIn: await this.cookiesLoggedIn(s.context).catch(() => false) }) : this.response(accountId); }
  async continue(accountId: string) { const s = this.requireActive(accountId); if (!await this.check(s.page)) { s.status = 'manual_intervention_required'; return this.response(accountId, s, { errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Complete Facebook login or verification in the browser, then continue.' }); } if (s.pending) return s.pending(); await this.close(s, 'completed'); return this.response(accountId, undefined, { sessionId: s.sessionId, status: 'completed', loggedIn: true }); }
  async cancel(accountId: string) { const s = this.requireActive(accountId); await this.close(s, 'cancelled'); return this.response(accountId, undefined, { sessionId: s.sessionId, status: 'cancelled' }); }
  private async manual(accountId: string, current: ActiveSession, url: string, pending?: () => Promise<WorkerResponse>) { await this.close(current, 'cancelled'); const session = await this.open(accountId, true); await session.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45_000 }); session.status = 'manual_intervention_required'; session.pending = pending; return session; }
  async validate(accountId: string) { const current = this.sessions.get(this.byAccount.get(accountId) ?? ''); if (current) return this.response(accountId, current, { loggedIn: await this.check(current.page) }); const s = await this.open(accountId); try { await s.page.goto('https://www.facebook.com/', { waitUntil: 'domcontentloaded', timeout: 45_000 }); const loggedIn = await this.check(s.page); if (!loggedIn) { const m = await this.manual(accountId, s, 'https://www.facebook.com/'); return this.response(accountId, m, { loggedIn: false, errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Login or verification is required.' }); } await this.close(s, 'completed'); return this.response(accountId, undefined, { sessionId: s.sessionId, status: 'completed', loggedIn: true }); } catch (e) { await this.close(s, 'failed'); throw e; } }
  private async usePage(accountId: string, url: string) { const existing = this.sessions.get(this.byAccount.get(accountId) ?? ''); const s = existing ?? await this.open(accountId); await s.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45_000 }); return { s, transient: !existing }; }
  async inspect(accountId: string, postUrl: string) { const { s, transient } = await this.usePage(accountId, postUrl); const security = await detectSecurityState(s.page); if (security !== 'ready' || !await this.cookiesLoggedIn(s.context)) { const m = transient ? await this.manual(accountId, s, postUrl) : s; m.status = 'manual_intervention_required'; return this.response(accountId, m, { errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Login or verification is required before inspecting this post.' }); } const result = await inspectVisiblePost(s.page); if (transient) await this.close(s, 'completed'); return this.response(accountId, transient ? undefined : s, { status: 'completed', loggedIn: true, result }); }
  async execute(accountId: string, input: ActionRequest) {
    const fingerprint = this.approvals.fingerprint(accountId, input.postUrl, input.action, input.action === 'react' ? input.reaction : undefined, input.action === 'comment' ? input.comment : undefined);
    const started = await this.approvals.begin(accountId, input.approvalId, fingerprint);
    if (started.duplicate) return this.response(accountId, undefined, { status: started.record.status as SessionStatus, errorCode: started.record.status === 'outcome_unknown' ? 'OUTCOME_UNKNOWN' : null, result: { approvalId: input.approvalId, idempotent: true, previousState: started.record.previousState ?? null, finalState: started.record.finalState ?? null } });
    return this.perform(accountId, input, started.record);
  }
  private async perform(accountId: string, input: ActionRequest, record: ApprovalRecord): Promise<WorkerResponse> {
    const { s, transient } = await this.usePage(accountId, input.postUrl); const security = await detectSecurityState(s.page);
    if (security !== 'ready' || !await this.cookiesLoggedIn(s.context)) { const m = transient ? await this.manual(accountId, s, input.postUrl, () => this.perform(accountId, input, record)) : s; m.status = 'manual_intervention_required'; m.pending = () => this.perform(accountId, input, record); await this.approvals.complete(record, 'manual_intervention_required'); return this.response(accountId, m, { errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Complete Facebook verification in the browser, then press Continue.' }); }
    s.status = 'running';
    try {
      const result = input.action === 'react' ? await this.react(s.page, input.reaction) : await this.comment(s.page, input.comment);
      if (result.confirmed) { await this.approvals.complete(record, 'completed', result.previous, result.final); if (transient) await this.close(s, 'completed'); return this.response(accountId, transient ? undefined : s, { status: 'completed', loggedIn: true, result: { approvalId: input.approvalId, previousState: result.previous, finalState: result.final } }); }
      await this.approvals.complete(record, 'outcome_unknown', result.previous, result.final); s.status = 'outcome_unknown'; return this.response(accountId, s, { errorCode: 'OUTCOME_UNKNOWN', errorMessage: 'The final Facebook state could not be confirmed.', result: { approvalId: input.approvalId, previousState: result.previous, finalState: result.final } });
    } catch {
      const security = await detectSecurityState(s.page).catch(() => 'ready');
      if (security !== 'ready') { const m = transient ? await this.manual(accountId, s, input.postUrl, () => this.perform(accountId, input, record)) : s; m.status = 'manual_intervention_required'; m.pending = () => this.perform(accountId, input, record); await this.approvals.complete(record, 'manual_intervention_required'); return this.response(accountId, m, { errorCode: 'MANUAL_INTERVENTION_REQUIRED', errorMessage: 'Facebook requires manual verification before this approved action can finish.' }); }
      await this.approvals.complete(record, 'outcome_unknown'); s.status = 'outcome_unknown'; return this.response(accountId, s, { errorCode: 'OUTCOME_UNKNOWN', errorMessage: 'The action result could not be confirmed; it was not retried.', result: { approvalId: input.approvalId } }); }
  }
  private async react(page: Page, requested: Reaction) { const selected = page.locator('[aria-pressed="true"]').last(); const previousLabel = (await selected.getAttribute('aria-label').catch(() => null) ?? '').toLowerCase(); const previous = reactions.find((x) => previousLabel.includes(x)) ?? null; if (previous === requested) return { confirmed: true, previous, final: requested }; const like = page.getByRole('button', { name: /^like$/i }).last(); if (requested === 'like') { await like.click({ timeout: 5000 }); } else { await like.hover({ timeout: 5000 }); await page.waitForTimeout(700); const target = page.locator(`[aria-label="${requested[0].toUpperCase()}${requested.slice(1)}"]`).last(); if (await target.count()) await target.click(); else await page.getByText(new RegExp(`^${requested}$`, 'i')).last().click(); } await page.waitForTimeout(900); const state = (await page.locator('[aria-pressed="true"]').last().getAttribute('aria-label').catch(() => null) ?? '').toLowerCase(); const final = reactions.find((x) => state.includes(x)) ?? null; return { confirmed: final === requested, previous, final }; }
  private async comment(page: Page, text: string) { if (!text.trim()) throw new ApiError('INVALID_COMMENT', 'comment must be non-empty.'); const before = await page.locator('body').innerText(); if (before.includes(text)) return { confirmed: true, previous: 'existing_comment', final: 'existing_comment' }; const composer = page.locator('[contenteditable="true"][role="textbox"], textarea').last(); if (!await composer.count()) { await page.getByRole('button', { name: /^comment$/i }).last().click({ timeout: 5000 }); } const activeComposer = page.locator('[contenteditable="true"][role="textbox"], textarea').last(); if (!await activeComposer.count()) return { confirmed: false, previous: null, final: null }; await activeComposer.click(); await activeComposer.fill(text); await activeComposer.press('Enter'); await page.waitForTimeout(1200); const after = await page.locator('body').innerText(); return { confirmed: after.includes(text), previous: null, final: after.includes(text) ? 'comment_present' : null }; }
  private async close(s: ActiveSession, status: SessionStatus) { clearTimeout(s.timeout); this.sessions.delete(s.sessionId); this.byAccount.delete(s.accountId); try { await s.context.close(); } finally { await s.release(); } s.status = status; }
  private async externalClose(s: ActiveSession) { if (!this.sessions.has(s.sessionId)) return; clearTimeout(s.timeout); this.sessions.delete(s.sessionId); this.byAccount.delete(s.accountId); await s.release(); }
  async shutdown() { await Promise.all([...this.sessions.values()].map((s) => this.close(s, 'cancelled'))); }
}
